<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.indi-an.plccom.examples</groupId>
    <artifactId>plccom-opc-ua-sdk-examples-java</artifactId>
    <version>10.6.2</version>
    <packaging>pom</packaging>

    <name>PLCcom OPC UA SDK for Java - Workshop Examples</name>

    <modules>
        <module>PLCcom.Console</module>
        <module>Client_Server_Samples</module>
        <module>PubSub_Samples</module>
    </modules>
</project>
