// MIT License
// Copyright (c) Indi.An GmbH

// ==============================================================================
// PLCcom OPC UA Server SDK - Workshop 51: Logging
//
// The SDK exposes the OPC UA stack's internal trace messages through the
// UaLogListener interface. This lets you route SDK diagnostics to your own
// logging framework (Log4j, SLF4J, java.util.logging, etc.)
//
// Log levels (from least to most verbose):
//   Error   -> only errors that affect functionality
//   Warning -> errors + warnings (recommended for production)
//   Info    -> errors + warnings + service calls (connect, read, write, subscribe)
//   Debug   -> everything including internal stack details (very verbose)
//
// Use cases:
//   * Troubleshooting connection problems
//   * Auditing client access (who connected, what they read/wrote)
//   * Performance monitoring
//   * Integration with your application's logging infrastructure
//
// What you will learn:
//   * How to subscribe to SDK log messages via UaLogListener
//   * How to set the log verbosity level
//   * How to filter and format log messages
//   * How to route logs to your own framework
//
// Connect with any OPC UA client to: opc.tcp://localhost:48410
// ==============================================================================

import com.plccom.opc.ua.core.UserTokenPolicy;
import com.plccom.opc.ua.server.application.*;
import com.plccom.opc.ua.server.application.UaServerNodes.*;

public class _51_Logging {

    public static void main(String[] args) throws Exception {

        PLCcomConsole.open("Workshop 51 - Logging", 1000);

        String licenseUser   = "<Enter your UserName here>";
        String licenseSerial = "<Enter your Serial here>";

        System.out.println("╔══════════════════════════════════════════════════════════════╗");
        System.out.println("║  PLCcom OPC UA Server SDK - Workshop 51: Logging             ║");
        System.out.println("║                                                              ║");
        System.out.println("║  This example demonstrates:                                  ║");
        System.out.println("║  * Subscribing to SDK log messages                           ║");
        System.out.println("║  * Setting log verbosity (Error, Warning, Info, Debug)       ║");
        System.out.println("║  * Filtering log messages by level                           ║");
        System.out.println("║  * Routing logs to your own framework                        ║");
        System.out.println("╚══════════════════════════════════════════════════════════════╝");
        System.out.println();

        UaServerConfiguration config = createConfig();
        printConfig(config);

        try (UaServer server = new UaServer(licenseUser, licenseSerial)) {

            System.out.println("  License: " + server.getLicenceMessage());
            System.out.println();

            server.addCertificateValidationListener(e -> e.setAccept(true));

            // -- Subscribe to log messages -----------------------------------------
            // addLogListener() fires for every message that passes the current log level.
            // Register BEFORE calling start() to capture startup messages.
            // In production, replace System.out with your logging framework call.
            server.addLogListener(e -> {
                // Example: forward to SLF4J or Log4j:
                // switch (e.getLevel()) {
                //     case Error:   logger.error(e.getMessage(), e.getException()); break;
                //     case Warning: logger.warn(e.getMessage()); break;
                //     case Info:    logger.info(e.getMessage()); break;
                //     default:      logger.debug(e.getMessage()); break;
                // }
                System.out.printf("  [%-7s] %s%n", e.getLevel(), e.getMessage());
            });

            // -- Set log level -----------------------------------------------------
            // setLogLevel() controls which messages are generated by the OPC UA stack.
            // Call this before start() to capture startup messages at the desired level.
            // Changing the level at runtime is also supported.
            //
            //   Error   -> only errors (minimal output, good for production)
            //   Warning -> errors + warnings
            //   Info    -> errors + warnings + service calls (good for development)
            //   Debug   -> everything (very verbose, use only for troubleshooting)
            server.setLogLevel(UaLogLevel.Info);

            System.out.println("  Log level set to: Info");
            System.out.println("  (connect a client to see log messages appear here)");
            System.out.println();

            System.out.print("  Starting server ... ");
            try {
                server.start(config);
            } catch (Exception ex) {
                System.out.println("FAILED: " + ex.getMessage());
                System.in.read();
                PLCcomConsole.close();
                return;
            }
            System.out.println("OK");
            for (String addr : config.getBaseAddresses())
                System.out.println("  Endpoint: " + addr);
            System.out.println();

            UaFolder plant = server.createFolder("Plant", UaRolePermissions.WITHOUT_RESTRICTIONS);
            server.createVariable(plant, "Temperature",
                    UaRolePermissions.WITHOUT_RESTRICTIONS, Double.class, 22.0, false);

            System.out.println("╔══════════════════════════════════════════════════════════════╗");
            System.out.println("║  Server is running with logging enabled.                     ║");
            System.out.println("║                                                              ║");
            System.out.println("║  Endpoint: opc.tcp://localhost:48410                         ║");
            System.out.println("║                                                              ║");
            System.out.println("║  Try:                                                        ║");
            System.out.println("║  * Connect a client - see the session creation log entry     ║");
            System.out.println("║  * Read Temperature - see the Read service log entry         ║");
            System.out.println("║  * Subscribe to Temperature - see subscription log entries   ║");
            System.out.println("║  * Disconnect - see the session close log entry              ║");
            System.out.println("║                                                              ║");
            System.out.println("║  Press ENTER to exit.                                        ║");
            System.out.println("╚══════════════════════════════════════════════════════════════╝");
            System.in.read();
        }

        PLCcomConsole.close();
    }

    private static UaServerConfiguration createConfig() {
        UaServerConfiguration config = new UaServerConfiguration();
        config.setApplicationName("PLCcom Workshop 51 - Logging");
        config.setApplicationUri("urn:localhost:PLCcom:Workshop:51");
        config.setProductUri("https://www.indi-an.com/en/plccom/opc-ua-sdk/opcua-overview/");
        config.setNamespaceUri("http://indi-an.com/opcua/workshop/logging");
        config.setManufacturerName("My Company GmbH");
        config.setProductName("My OPC UA Server");
        config.setSoftwareVersion("1.0.0");
        config.setBuildNumber("42");
        config.setBaseAddresses(java.util.Arrays.asList(
                "opc.tcp://localhost:48410", "opc.https://localhost:48411"));
        config.setSecurityModes(UaServer.getRecommendedSecurityModes());
        config.setUserTokenPolicies(java.util.Arrays.asList(UserTokenPolicy.ANONYMOUS));
        config.setCertificateStorePath("./pki");
        config.setCertificateLifetimeInMonths(60);
        config.setAutoAcceptUntrustedCertificates(false);
        config.setMaxSessionCount(100); config.setShutdownDelay(5);
        config.setVendorName("My Company GmbH");
        config.setVendorProductName("My OPC UA Server");
        config.setVendorProductVersion("1.0.0");
        config.setHttpsSecurityPolicies(java.util.Arrays.asList(
                com.plccom.opc.ua.transport.security.HttpsSecurityPolicy.TLS_1_2_PFS,
                com.plccom.opc.ua.transport.security.HttpsSecurityPolicy.TLS_1_3));
        config.setMaxNodesPerRead(1000); config.setMaxNodesPerWrite(1000);
        config.setMaxNodesPerBrowse(1000); config.setMaxNodesPerHistoryReadData(100);
        config.setMaxNodesPerHistoryReadEvents(100); config.setMaxNodesPerHistoryUpdateData(100);
        config.setMaxNodesPerHistoryUpdateEvents(100); config.setMaxNodesPerMethodCall(200);
        config.setMaxNodesPerRegisterNodes(1000);
        config.setMaxNodesPerTranslateBrowsePathsToNodeIds(1000);
        config.setMaxNodesPerNodeManagement(1000); config.setMaxMonitoredItemsPerCall(1000);
        // AsConfigured (default) = endpoints use exactly the host from BaseAddresses
        // NormalizeToHostname    = replace localhost/127.0.0.1 with the machine name
        config.setEndpointHostMode(UaEndpointHostMode.AsConfigured);
        return config;
    }

    private static void printConfig(UaServerConfiguration config) {
        System.out.println("── Active Server Configuration ──────────────────────────────");
        System.out.println("  ApplicationName : " + config.getApplicationName());
        System.out.println("  ApplicationUri  : " + config.getApplicationUri());
        System.out.println("  NamespaceUri    : " + config.getNamespaceUri());
        System.out.println("  Endpoints:");
        for (String addr : config.getBaseAddresses()) System.out.println("    " + addr);
        System.out.println("─────────────────────────────────────────────────────────────");
        System.out.println();
    }
}
